name: SkyRiseCore
version: '${project.version}'
main: pl.skyrise.skyRiseCore.SkyRiseCore
api-version: '1.21'
description: All-in-one modular plugin
authors: [SkyRise]
softdepend: [Vault]

commands:
  skyrisecore:
    description: Główna komenda pluginu
    usage: /skyrisecore <reload|list|version>
    aliases: [src]
    permission: skyrise.admin
  adminchat:
    description: AdminChat — prywatny czat administracji
    usage: /ac [wiadomość]
    aliases: [ac]
    permission: skyrise.adminchat
  globalchat:
    description: Czat globalny
    usage: /g <wiadomość>
    aliases: [g]
  armorworld:
    description: Zarządzanie blokadami zbroi na światach
    usage: /armorworld <add|remove|list|items|off>
    aliases: [aw]
    permission: skyrise.armorworld.admin
  me:
    description: Komenda narracyjna /me
    usage: /me <akcja>
  do:
    description: Komenda narracyjna /do
    usage: /do <opis>
  try:
    description: Komenda narracyjna /try
    usage: /try <próba>
  opis:
    description: Opis postaci
    usage: /opis <treść>
  opis2:
    description: Opis miejsca stojącego
    usage: /opis2 <treść>
  freeze:
    description: Zamrażanie graczy
    usage: /freeze <gracz>
    aliases: [fz]
    permission: skyrise.freeze
  unfreeze:
    description: Odmrażanie graczy
    usage: /unfreeze <gracz>
    aliases: [ufz]
    permission: skyrise.freeze
  setfreeze:
    description: Ustawianie punktu freeze
    usage: /setfreeze
    permission: skyrise.freeze
  delfreeze:
    description: Usuwanie punktu freeze
    usage: /delfreeze
    aliases: [delfz]
    permission: skyrise.freeze


  butelkomat:
    description: Komenda butelkomatu
    usage: /bm
    aliases: [bm]
    permission: butelkomat.admin

permissions:
  skyrise.*:
    description: Dostęp do wszystkiego
    default: op
    children:
      skyrise.admin: true
      skyrise.adminchat: true
      skyrise.armorworld.admin: true
      skyrise.armorworld.bypass: true
      skyrise.batspawn.admin: true
      skyrise.globalchat: true
      skyrise.globalchat.bypass: true
      skyrise.freeze: true
      skyrise.doctor: true
  skyrise.admin:
    description: Dostęp do /skyrisecore
    default: op
  skyrise.adminchat:
    description: Dostęp do AdminChat
    default: op
  skyrise.armorworld.admin:
    description: Zarządzanie blokadami zbroi
    default: op
  skyrise.armorworld.bypass:
    description: Omijanie blokady zbroi na światach
    default: false
  skyrise.globalchat:
    description: Dostęp do czatu globalnego
    default: true
  skyrise.globalchat.bypass:
    description: Omijanie cooldownu czatu globalnego
    default: op
  skyrise.freeze:
    description: Uprawnienia do zamrażania graczy
    default: op
  skyrise.doctor:
    description: Uprawnienia lekarza (widoczność powaleń i kordów)
    default: op
