# ══════════════════════════════════════
# SkyRiseCore — Config BatSpawn
# ══════════════════════════════════════

# Maksymalna wysokość Y na której mogą spawnować się nietoperze
max-y: 40

# Bloki na których mogą się spawnować (nazwy Material z Bukkit)
allowed-blocks:
  - STONE
  - DEEPSLATE

# Wiadomość przy próbie zablokowanego spawnu (MiniMessage)
# Zmienne: {max_y}
deny-message: "<red>»</red> <red>Nietoperze mogą spawnować się tylko poniżej Y {max_y} na blokach stone/deepslate."
