# ══════════════════════════════════════
# SkyRiseCore — Config AdminChat
# Format: MiniMessage <tagi>
# ══════════════════════════════════════

# Permisja wymagana do używania AdminChat
permission: "skyrise.adminchat"

# Wiadomości — MiniMessage tagi
messages:
  # Format wiadomości na AC
  # Zmienne: {player}, {message}
  format: "<dark_gray>[<dark_red>ADMIN</dark_red>]</dark_gray> <red>{player} »</red> <white>{message}"

  # Toggle — powiadomienia
  toggle-on: "<#99CCFF>»</#99CCFF> <green>AdminChat włączony."
  toggle-off: "<#99CCFF>»</#99CCFF> <red>AdminChat wyłączony."
