# ══════════════════════════════════════
# SkyRiseCore — Config Freeze
# ══════════════════════════════════════

# Wiadomość wysyłana na czat zamrożonemu graczowi (MiniMessage)
# Możesz tu używać klikalnych linków do Discorda!
freeze-chat: "<red>»</red> <red>Zostałeś/aś zamrożony/a! Wejdź pilnie na nasz Discord: <click:open_url:'https://discord.gg/lekoland'><yellow><underlined>discord.gg/lekoland</underlined></yellow></click>"

# Wiadomość wyświetlana na pasku Actionbar co 2 sekundy (MiniMessage)
freeze-actionbar: "<red>»</red> <red>Zostałeś/aś zamrożony/a – wejdź na Discorda!"

# Permisja administracyjna dla freeze / unfreeze / setfreeze / delfreeze
permission: "skyrise.freeze"

# Zapisane dane freeze (zapisywane automatycznie przez serwer)
freeze-location: ""
frozen-players: {}
