# ══════════════════════════════════════
# SkyRiseCore — Config Knockout
# ══════════════════════════════════════

# Czas na podniesienie leżącego gracza (w sekundach) przed wykrwawieniem
bleedout-time: 30

# Czas potrzebny na podniesienie kogoś (w sekundach) przy kucaniu przy nim
revive-time: 5

# Wiadomości (MiniMessage)
messages:
  knocked-self: "<red>»</red> <red>Zostałeś/aś powalony/a! Masz {time}s na ratunek. Kliknij 3x Shift aby się wykrwawić."
  knocked-broadcast: "<red>» [DYSPOZYTORNIA]</red> <gray>Obywatel <white>{player}</white> został powalony! Lokalizacja: <gold>{world} ({x}, {y}, {z})</gold>"
  reviving-actionbar: "<gold>Podnoszenie: </gold>{bar}"
  revived-self: "<green>»</green> <green>Zostałeś/aś podniesiony/a przez <white>{player}</white>!"
  revived-other: "<green>»</green> <green>Podniosłeś/aś gracza <white>{player}</white>!"
  bleedout-broadcast: "<red>»</red> <red>Gracz <white>{player}</white> wykrwawił się na śmierć."
